[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "770f6c434ae9cb022375de7370b5cc13a2b56e19"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "ed08cd9ce1b243396a95bb55f74a6c8f084089073be8fce3fa5668c07b108f5c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "76086f0bedf3f16b01d48fe345d08490ac958f85"
lazy = true
mpi = "mpich"
os = "macos"

    [[nlcglib.download]]
    sha256 = "e937c60f9d7037ebc5481d3bedf5b7ce4415b654a66492eed449b466224bbac0"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "09bc923cb94b133a6038f106c1f9d6e1313e235a"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[nlcglib.download]]
    sha256 = "f1fcd4396ef860a948e10307452307e3ff9a9fca77bc4ff59df796ae3b568760"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "d6318c9407df839a045660f0a51b9e52c4b24ab1"
lazy = true
mpi = "openmpi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "ef1f46002d4fb2fe5d9b890822b8634b67b51a51498b65942d0d17df413b5511"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bf6e544f4f810268da2b11d090b9bbccc733005"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "3d22a3b04fc5f0734137c9d8d6fef4d517956aa97ec9cdc45cdcf41e73f34980"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffca4f769e5f91362c702fdbcfe95b736bc8fa9e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "9ec4226cdec1d789271ce0850351d2116d941ee0af831341b80a52d6bcde8e1c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e24237ed30a31699b37aafccee4faf85a4db18cc"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "dac85b1ae96a9eda31fd1a6cde300d39edc79313e3dd980599bc06bce80e1e88"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "884a2e469ac6944c5893a69a97aea5b95bccff2a"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "f280d66eb41844f532b7b96ff6ed10b8ad300cb90d3f36ca35b091a39a9c199b"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9991988455bc1093cef28c2877c68adaebae525"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "791b5d9f04a53ab449c898887f335c190764cde1a7b7e12564eaf948609f9de4"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81bb9a02c905f8271141076a15da468ee2e1aae3"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "0283b030148ac4f46fa9c1a7eab513057b3654f131ce947aa379f64b27aa2699"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84b004f20139f0eaba2eba347abacbe6b562de1f"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "e67446f2ddef5cdc2431a5c4b76b6ba80c7d3b90379dc854e6636ce8973f30a3"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "ee7e11c34af804b22420d528b01874613ad40e09"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "7315f7d8a131566f1589f2e6676882117a382b4aa11d9a04f6b3fc567d9c465b"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "ffe82393e4ef793b54c523b1bc7d6b6115fbecdb"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "74b351c7d4f85c759350705cc4f98e3872aeb0fbb33feb06b1b54539f96a3850"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "91967a0bd3ebfe5b3f4f5ddfbb4dc416fc86d926"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "e8c4f30f0f009a80b77fa9cc6eb3d983df5e9268e4524407b86c003befa2abfb"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "1bb645e552a8536c57977c21185c139438e52080"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "4af04052dafb5336f3f010a36f3087badfbacacf4cac8d7a6e78623880fa1fce"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4bc8c42633920d1f076444ff8eea848a295ede8"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "d118e31f48ed190d1e5c259e3aff8680cc23c8a3c01d959e0fbdab7d29e47012"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.powerpc64le-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbfd4f963186ba9de8ee74b9077424a840b8ba1c"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "a8cc10aea7b1a3dc2225e294c3ffec9a609ed6ce156c65f937acb209c81312a4"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14fc7c539da057cd9274061f56fb208f1ea083c4"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "2930c64408b348d5457c2148983de3fd8ee14540634e28047617ff68511178c4"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32dda1898b3104f7de4592ee65db70242dfa175f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "d7688ae265b37846aacb13939838aa35903b69d5ae240c0b346fe100131ece9c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "499194ba978d626e21708f84b1765c399420a768"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "74b5805275c9a43c4488c4e11d1e6865f25ab39b1b5916e5ef95cbe21ba742d6"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.riscv64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89f5141ba090b83a20f0b270c3ef86f5e8a47073"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "094f042c3fbf7b47cf1f2210d22e4403e89c54cc09b2356e58636406efe8bc24"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "498c454a5812eb769551b59810d04727fb0a2b94"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "0aff88ceed0f2253fa4e5c1b94339c414ee5404f27524c51813e77b6f730c225"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.riscv64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12b5fc2ae14e2ac743ccede75fc8a9ffea479a67"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "35e6f1c914ed15ff33dec972f6faa637dac856557b3d20aa51c6846e31f668f5"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "fea57924ad8569b065602d13f6c489175dbf4a27"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "0029ba184e074412615fcdf0b1fc47c6b3ab290343db083412ae13ea9354472d"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "150baf3fcc20bcb9e0d6ce86dd9a06e83b10df16"
lazy = true
mpi = "mpich"
os = "macos"

    [[nlcglib.download]]
    sha256 = "d25c403cfa354b794dc244e0a92b03bb0d098ff96b8b58711057ba4829026bbd"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "ef28783f24eb8f2af264e786bf1bb943eb87bae3"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[nlcglib.download]]
    sha256 = "fe10f5f828e322e973117e12b246ad879867f35cd07149dbcaa6cd72b0e501c9"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "fc2435ebf585b8babc2b38913563c6b4e6527db5"
lazy = true
mpi = "openmpi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "4b11f7c725ca1e965c448b8287077ec00b34e749b6767ff24251232feec26cb1"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61d00d4cba470036975ce140bacdd21cf0adc84e"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "798dd60aa0f8bba6f2ce5437a8fb49e7c27c7ae332ed77d0b895afbd0c1d31f6"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e0cfda9dd482a07f341bf019b8de450c3c811d7"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "8aaa26f81e4af0f3f8343afb9ea6516a27090fe9a04ab70c8c6c05c1b7feb241"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc4dc0db5b6c539570564309660b40b585b17926"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "231d2d9c3997e3c59e9c3f50bb3ea8ef9f36544c35d290cbfccb3a36a1fb048c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b272c7fbe425ea56db0d7cf2089d371c9e9e7134"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "dce30d53c998c555c54a7b4268694ccda486dc81b7c21243115ac6ba76fc3dfc"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56b934a512b730f4bd65df46526da9067ebcc3ed"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "6cdbd7e98269e96b554d91e254ff6fd2318ed67121c4fc99678ef88b14bbd62d"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac1d94d9f0f6bf6e431eb6fa314293c515445c0f"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "96856d912dab84b6d309bf210071ebac4e0f7713b2530eaa9e6023321f792354"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfdb285b41c99e70f089e4ba31dd05f2d30caba4"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "7079421ed15a0e1c3e563d53c368605439f54bb1899d5315d77c3d743da21f04"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "89889f6a14e0b2669da73388ffafa6bb66869f92"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "ddd8da7eefdf201354f4df781fe9b06b6dc3077454f2d5f94c6209dd7b9e2b03"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "abe0575e7100de16b49902c6c20bc2451e9d11fa"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "3e00f7fd59e7b4715018c2a47ad66cee2e3abcce99b375196ced4184e173e2d0"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "9f935220cfeedc178e05d063a891020a89b81f2b"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "4697b2e589d4de135f07ba8d3cd08ea7577e4c50e913070e62a75866ac4322b7"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "a8b825fdcf8cdbe7c7b2754ce8443d2e279d413f"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "bf55bdd40e94388cdfbdbc06be502a1b5f6c0f5bb19131858d28bd136990f617"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.1+0/nlcglib.v1.1.1.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
