[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "2f3e5d19d3ef52c97a31326e3baf52bcb596c23c"
lazy = true
mpi = "mpich"
os = "macos"

    [[nlcglib.download]]
    sha256 = "91aec046f448c48e6a492ffca963a226723e2f82e89672576c2cfb015d46e806"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "9fcb4380db50f2fc6b319f134f49c8a7cde7dd65"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[nlcglib.download]]
    sha256 = "c08d6d85e8b7b87016ed584a9489cbc081707791da9cea51c71602ea14e3fd20"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "a99d421086eb0ab261a322bd0773128f531cc6f9"
lazy = true
mpi = "openmpi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "75f448f88df91ac2d2d906356d57f8bc17d2e0f32542549a38c9e45bf3b72c14"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6e15a7ee3d67c2305376226869a4f7fdc981c36"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "85567882c92ac3636a57ae9b6656e19f5083555c81568bb6e093d4f149dca07a"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10292ea3c4f85fec9457211f2e2189ad884735ae"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "97d40470b5bbb33b04bc0c185b3dbbbe5fb33fb7eac390d14822e2195895668e"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a12883d40eadf37755037f1882be45326a29781"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "179eab2cf7fe6548d2b34b781c1f86190651b5fe1b7a0640c8f053f9b4cabccd"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e1ac10280239e5294cd0e8ccc67c1e6472c9aaf"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "7ac7da9532d9d7d93f22bc45ec88e0ebdbd3097faf304b9be3a912935df0372c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4cc25dd3fa4573b04c11300f71154f7faad9cfc"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "7f367ba8bfd810840e7713fd1264c0a3f0e9d386fa4851a975a610bff97ccaef"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca45341d4293a44496ff3908537681235f267bde"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "45afadb9e0bb92b9f21aa4d545da3a7ae933ae4f3938c4ca3e9333f6888f9354"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8cb0e76150cabc5d2a19bbf0608cf8f54a221c54"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "06e8009130b68f37fd04bf5db7bb0c7c9a3b4863a54281ecb8a67c4552f1e3e2"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-musl-cxx03-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e74d3e174205dc7ad8987ae19c853701d1524c18"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "931008d782078b5ad5518881a1174eb96cf676e9bbd73bbd26e4189984777bdf"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-musl-cxx03-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd910e9001e304c1d745bcc238000aa8670d02f4"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "10f0f32ec38066eaa859ee496fb4a56d0c465a9d48f35892bbd0781e9ec3206a"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a0607f1eca40e41693f1cdd08cf2c5afa08a59f"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "30bee69ed1781edef58078daf43e5798476c5b23e55203426f3781900fd95909"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "148ce9c8d3231758e4609bbe0c18785f22fa51f8"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "4ea794d6ce4db855a1a08cca44851cb20d7fb6d6a5b4dc61097432e27c9f3830"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.powerpc64le-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ee7aa98d41974673266d0b26a69e577a84064df"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "33cb2c3963f75a479ba9d27c028ee84812ad345b88d0fe3030ad306fa2bd8b9f"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.powerpc64le-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66558cb2bda2022eb8bf1a18546523bf42e88a8f"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "beabce2c0e77bfd3bc026a7e808df606926e63fe621a8425b0917614365c2e59"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.powerpc64le-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a141c93e74f0d280db7a46e4312c9ff9bb87e406"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "ccf9296ed6ea7858f5a14df12977bd5a5cd80b33ac9d124e54b1e7a0b8898545"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c1f41e00437d06a37a8aa50b7325718dc48db26"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "e122f9ffc61f13dd322858dff1cbe7d8ac8305b40181f16b8f937112f1636138"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2208468ee126bbb8f2808d86ab44398cfb035637"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "93ce5714bce1afa1327209b1ee3b5dfb3bfbadada655626623d07eb3d3264a89"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "5b87fb6b56f24a91c5b089bd6fedd1c048e9d6c0"
lazy = true
mpi = "mpich"
os = "macos"

    [[nlcglib.download]]
    sha256 = "18bea249e7f7e5671a3ac7c9955b64b47a35a84b86a72d711d05491a3d20c467"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "eb2d9fa6a42ee8869593030724c0855aa83e706d"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[nlcglib.download]]
    sha256 = "c137e9aa41a84e5cfdf1ef11fbf928e35caf3cef98dd310c2c29f196618d1267"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "758a81b91c45343a1f23c86b97e8d9b5a437e2eb"
lazy = true
mpi = "openmpi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "bbe816a1d9f8386d935b937bad218047afa37f748c65dbc739c448bb500ce396"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cee6a843639a7702517e9eed48cbecf3918d40b4"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "fa169d61aec669e5e92bd4beb5c4f601f273517836b63707581a25b64823efa2"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-gnu-cxx03-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6884bc4429d9202277ef5647669d427b1bfc528c"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "9bc14d4adf956a460cdd6c99696f999a422013447f4f9c6fca1ac3d9fe1a4121"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-gnu-cxx03-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8484d1c38bc203c4a31b5c70184e209b6d629b17"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "5a106c823fdd2362d448e328f8573c15e60a1db0e924a0144f84b065b87ae713"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-gnu-cxx03-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2b45e02548fdbbb7d03240ffc446e271333d209"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "0282c0b2f0e99918b166da3d29e2e126002f2d7bab52b25f8a033f5d19250baa"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e655ea23682a3d358f122d5193d3473583220a35"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "5593441befa83ea5c9fe157f75ea8594d0947a549502650947486d860464e9fa"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "421c6374e7aa58003c38895515e8c8ed9d44a993"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "07ed3e74a790b93a4839e1d58003c53ec428f63292e312f14bc591eeb47ce04f"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbe44c8ae1ca1871d80c722744f9fc85bebe2cb4"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "7b6b96cd943a95a6cb0bb30dffce72782c2817aadc8675004cb41e87cc36f42b"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-musl-cxx03-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eab7f9553800ef29ac7371004638192b6d17e8cd"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "1012bb5af0691a3d2c518b4ce1e741baa15d3e8a1edee443f5ad4332fb039137"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-musl-cxx03-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0562bd44ddae76ea5a532f70bd82c0cc3cd4e1b2"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "a35721a5695949e9a88be9badf4a7fb1cff86677a5b0d55c95b8c9448bdcbbb2"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd643198d1ae37fa2379b4c10f238d80b37d4919"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "89f7b69b216829ca17fd12f5e03b0227492267ae9f7977cebc327753a937bc06"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.0+0/nlcglib.v1.1.0.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
