[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "ca42510f33bf25e219ecdc649fbf37f0798740f4"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "599cc3bf362b4650702d640565be47909e7a9ac181fed2dae4e1705ef7cb39d7"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "24a8ea0db5b57f40705bda4e39751bc3b0174b5b"
lazy = true
mpi = "mpich"
os = "macos"

    [[nlcglib.download]]
    sha256 = "27cf395fcabbd3a10d62f5aee496dd42cac28b765302b98958225d46557893c1"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "c1ac80f80e3a7f836a77c72dd9a163f407f7df3f"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[nlcglib.download]]
    sha256 = "1bbff6ca1214aed75b4fe4b7253dc9ebdc17f1dc93ea3b07885810180763988c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "7311c17016b13fb939cdba9fa2727b900e36d264"
lazy = true
mpi = "openmpi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "55122e356b63c95c51b1f99ae8ea2d415747155f8f7fe566515576cf50fb4499"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9a5e56a56051460bd957ce3bd47c69b3846a50f"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "76b73ac5ecd9a1b8ab1db8fbd08d1310908700efe9fce6e2ea7a130ef90a0a95"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffca4f769e5f91362c702fdbcfe95b736bc8fa9e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "9ec4226cdec1d789271ce0850351d2116d941ee0af831341b80a52d6bcde8e1c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e24237ed30a31699b37aafccee4faf85a4db18cc"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "dac85b1ae96a9eda31fd1a6cde300d39edc79313e3dd980599bc06bce80e1e88"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d52ee48faf4e4e348962286c9a76bc8cab6e9f84"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "a53750c5f37b176b6aeb21e0891f54284821400fc36b5505b23fbcc9df826233"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28c6069ceab270514ff2b5869485cdd4e8f1f3ea"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "ef453575a176048a860cf9950436cfb2bd7fa5cf96dd5633f662d0c0eea2d654"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81bb9a02c905f8271141076a15da468ee2e1aae3"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "0283b030148ac4f46fa9c1a7eab513057b3654f131ce947aa379f64b27aa2699"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1f73ea2e945d2ea8a60b766eec1868bd37dfd72"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "964b3abe36349fc6f9f81c4a236c212830cccbf4e6fae85196d54222f6416503"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "50281bf040db57c8990a54b0d339fbdbf659ac6b"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "3b482769e4e8260ecf65fa56cda01216b0a63b3f543e048d5e5174fb408526bc"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "c124537137942aec689e7eda23d0c9128f91e0f5"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "28a9d181b172f96b3e88189936e4e8969ee2ff124b002c2daf1ffeeb88096a04"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "44c72627b728da66192e9d218473c1c322956b4b"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "238e798d3cbfdc64a994253babfe1fef2fc94afa826b91faa58377048c3470d3"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "aarch64"
git-tree-sha1 = "349b3540145e11d4bd5d4ed0cfd6713928793b99"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "35eb1d4cec50d7f5adfdde03a5b8fcbb4931f7fdfadefe3571a6683d1cdcdd61"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.aarch64-unknown-freebsd-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e3ddc8b56312038012bbbd1259fff892a1e1e89"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "899daa091ed888a7291098dc145ce8bd937d2e2c7cd72819a6a3889c42a158ec"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.powerpc64le-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbfd4f963186ba9de8ee74b9077424a840b8ba1c"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "a8cc10aea7b1a3dc2225e294c3ffec9a609ed6ce156c65f937acb209c81312a4"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.powerpc64le-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14fc7c539da057cd9274061f56fb208f1ea083c4"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "2930c64408b348d5457c2148983de3fd8ee14540634e28047617ff68511178c4"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.powerpc64le-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0124bfb492cb3d901cf87da6467d1a9b9e6487ff"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "5528958f510951376056538f53eee718c2afd74063f2b1c2d67be9b60bf993c1"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.powerpc64le-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61b5a0c5aef437b8dd46dcc414f5bed3ac2376d9"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "b6fc7319309607806944b96285acfef4969805366786eddcb2d0efdd640bdbeb"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.riscv64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89f5141ba090b83a20f0b270c3ef86f5e8a47073"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "094f042c3fbf7b47cf1f2210d22e4403e89c54cc09b2356e58636406efe8bc24"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.riscv64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "498c454a5812eb769551b59810d04727fb0a2b94"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "0aff88ceed0f2253fa4e5c1b94339c414ee5404f27524c51813e77b6f730c225"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.riscv64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "600b6f3df69fc2616828247f71d018feedb7c9e8"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "eb9331e552eb4ddde8886882b81bc84792b0b2e32dafff762553f0478cb79786"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.riscv64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "a956ce26f64c2c2ce11cb5e162c5fa29208a14c7"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "897a93c0d2392428cfa80c9ee18661b6809d59a47c73e50b134951b554c7d960"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "7e24b0fea1e03699b66272a2ffdde9ad8fca5725"
lazy = true
mpi = "mpich"
os = "macos"

    [[nlcglib.download]]
    sha256 = "14a332d4665e45bb3de62074176a867f88bd34941774706762f49ee848ff4c09"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "f1d1e84f3e27d963d148d2895f3a1302c879289b"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[nlcglib.download]]
    sha256 = "a1f73e23ab529b98de77286648c6dd1138bb027c5e971246fc1319038df8681b"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "65c89a094215dd641a615b71ec4f64d8fec46432"
lazy = true
mpi = "openmpi"
os = "macos"

    [[nlcglib.download]]
    sha256 = "f908ee2ec76f62ef4cda1820b7c03fae07d9dbce18c32d1edb6c31393551adf6"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a7a352c973e5a5716304ddf4b20d745cc5d090e"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "27ad70404ad62a6a20170c14d66a9d1bda311b2f8923858e91f0d07e7e0aca85"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-linux-gnu-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e0cfda9dd482a07f341bf019b8de450c3c811d7"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "8aaa26f81e4af0f3f8343afb9ea6516a27090fe9a04ab70c8c6c05c1b7feb241"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-linux-gnu-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc4dc0db5b6c539570564309660b40b585b17926"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[nlcglib.download]]
    sha256 = "231d2d9c3997e3c59e9c3f50bb3ea8ef9f36544c35d290cbfccb3a36a1fb048c"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-linux-gnu-cxx11-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e550dbd73ab433753202fc8099a1c349a43c7c9"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "a79103187ac1f209016860c4dde2ff7b2af867117169dc8553f0dc2b32cdd5b1"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-linux-gnu-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b01366fa3d3f84ca023e5a6fc79d0111418d4e3a"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "522f0dc9ee9dedc5ae7d75ce222ab2cff4736929f3a632d0e8dd7d35e2745abb"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-linux-musl-cxx11-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac1d94d9f0f6bf6e431eb6fa314293c515445c0f"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[nlcglib.download]]
    sha256 = "96856d912dab84b6d309bf210071ebac4e0f7713b2530eaa9e6023321f792354"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-linux-musl-cxx11-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e381076fb9726ba7f1fd8be454555cd84d818f71"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[nlcglib.download]]
    sha256 = "1d6967320d6cf2135df4cd2327b0859dcd053acb263e4f86cbdad47104ac46c6"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-linux-musl-cxx11-mpi+openmpi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "cccf919bb1b7ae93f101a855ac3631262061d5ce"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "538a4c06eecea66dfbcbf1c5c47a8684ee57fbe0ca6083c8d55924878c87f9fd"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "28b8e1d8d803127893c384cc6a1e7b40092c0ac8"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "56d8c0fa9bc727d02963dff4de3a6c14466620ad20bd609bd269cd92fa9d292f"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "98ec36036526ad2f73c35e4fc2bc1da550827d8a"
lazy = true
mpi = "mpitrampoline"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "e00524142ae6b16c9b2194eae463670138e1780f37f9e67ade23b3de85ee785f"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-unknown-freebsd-mpi+mpitrampoline.tar.gz"
[[nlcglib]]
arch = "x86_64"
git-tree-sha1 = "9d373646670488dcf4aba1141c767af04897e1b1"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[nlcglib.download]]
    sha256 = "18d52ff825c3dee7272e5748bcb9c1b91fb0af86b08413a466b63f5be4f84d32"
    url = "https://github.com/JuliaBinaryWrappers/nlcglib_jll.jl/releases/download/nlcglib-v1.1.2+0/nlcglib.v1.1.2.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
